<?php

return [
    'audits' => [
        'create-case' => [
            'page_route' => 'new-case-view',
            'submit_route' => 'new-case-post',
            'method' => 'POST',
            'safety' => 'rollback',
            'payload' => 'create_case',
            'expected_fields' => [
                'doctor',
                'patient_name',
                'caseId1',
                'caseId2',
                'caseId3',
                'caseId4',
                'impression_type',
                'delivery_date',
                'units',
                'jobType',
                'material_id',
                'color',
                'style',
            ],
            'expected_statuses' => [302],
            'fail_on_session_error' => true,
        ],
        'tools-create-case' => [
            'page_route' => 'tools.create-case',
            'submit_route' => 'tools.store-case',
            'method' => 'POST',
            'safety' => 'rollback',
            'payload' => 'tools_create_case',
            'expected_fields' => [
                'stage',
                'phase',
                'amount',
                'jaw_teeth',
                'jaw_selection',
                'units',
                'job_type_id',
                'material_id',
            ],
            'expected_statuses' => [302],
            'fail_on_session_error' => true,
        ],
        'create-doctor' => [
            'page_route' => 'new-dentist-view',
            'submit_route' => 'new-dentist',
            'method' => 'POST',
            'safety' => 'rollback',
            'payload' => 'create_doctor',
            'expected_fields' => [
                'dentist_name',
                'phone_number',
                'address',
                'clinic_phone',
                'doc_password',
                'clinic_password',
                'material',
                'discount',
                'type',
            ],
            'expected_statuses' => [302],
            'fail_on_session_error' => true,
        ],
        'create-material' => [
            'page_route' => 'material-add',
            'submit_route' => 'material-add-post',
            'method' => 'POST',
            'safety' => 'rollback',
            'payload' => 'create_material',
            'expected_fields' => [
                'mat_name',
                'price',
                'jobTypes[]',
                'count_as_unit',
                'design',
                'manufacturing',
                'furnace',
            ],
            'expected_statuses' => [302],
            'fail_on_session_error' => true,
        ],
        'create-job-type' => [
            'page_route' => 'new-job-type-view',
            'submit_route' => 'new-job-type',
            'method' => 'POST',
            'safety' => 'rollback',
            'payload' => 'create_job_type',
            'expected_fields' => [
                'jobtype_name',
                'teeth_or_jaw',
            ],
            'expected_statuses' => [302],
            'fail_on_session_error' => true,
        ],
        'create-lab' => [
            'page_route' => 'new-lab-view',
            'submit_route' => 'new-lab',
            'method' => 'POST',
            'safety' => 'rollback',
            'payload' => 'create_lab',
            'expected_fields' => [
                'lab_name',
                'lab_phone',
                'lab_address',
            ],
            'expected_statuses' => [302],
            'fail_on_session_error' => true,
        ],
        'create-implant' => [
            'page_route' => 'new-implant-view',
            'submit_route' => 'new-implant',
            'method' => 'POST',
            'safety' => 'rollback',
            'payload' => 'create_implant',
            'expected_fields' => [
                'implant_name',
            ],
            'expected_statuses' => [302],
            'fail_on_session_error' => true,
        ],
        'create-abutment' => [
            'page_route' => 'new-abutment-view',
            'submit_route' => 'new-abutment',
            'method' => 'POST',
            'safety' => 'rollback',
            'payload' => 'create_abutment',
            'expected_fields' => [
                'abutment_name',
            ],
            'expected_statuses' => [302],
            'fail_on_session_error' => true,
        ],
        'create-tag' => [
            'page_route' => 'new-tag-view',
            'submit_route' => 'new-tag',
            'method' => 'POST',
            'safety' => 'rollback',
            'payload' => 'create_tag',
            'expected_fields' => [
                'tag_text',
                'tag_color',
                'tag_icon',
            ],
            'expected_statuses' => [302],
            'fail_on_session_error' => true,
        ],
        'create-failure-cause' => [
            'page_route' => 'new-f-cause-view',
            'submit_route' => 'new-f-cause',
            'method' => 'POST',
            'safety' => 'rollback',
            'payload' => 'create_failure_cause',
            'expected_fields' => [
                'cause_text',
            ],
            'expected_statuses' => [302],
            'fail_on_session_error' => true,
        ],
        'create-device' => [
            'page_route' => 'new-device-view',
            'submit_route' => 'new-device',
            'method' => 'POST',
            'safety' => 'rollback',
            'payload' => 'create_device',
            'expected_fields' => [
                'device_name',
                'device_type',
                'device_image',
            ],
            'expected_statuses' => [302],
            'fail_on_session_error' => true,
        ],
        'create-user' => [
            'page_route' => 'new-user-view',
            'submit_route' => 'new-user',
            'method' => 'POST',
            'safety' => 'rollback',
            'payload' => 'create_user',
            'expected_fields' => [
                'first_name',
                'last_name',
                'name_initials',
                'phone',
                'email',
                'username',
                'is_admin',
                'password',
                'password_confirmation',
                'permission[]',
            ],
            'expected_statuses' => [302],
            'fail_on_session_error' => true,
        ],
        'create-type' => [
            'page_route' => 'types.create',
            'submit_route' => 'types.store',
            'method' => 'POST',
            'safety' => 'rollback',
            'payload' => 'create_type',
            'expected_fields' => [
                'material_id',
                'name',
                'description',
                'is_enabled',
            ],
            'expected_statuses' => [302],
            'fail_on_session_error' => true,
        ],
    ],
];
