<?php return array (
  'projectNameShort' => 'SIGMA',
  'activeColor' => '#007bff',
  'waitingColor' => '#fd397a',
  'environment' => 'production',
  'labWorkFlowLabel' => 'Operations Dashboard',
  'sidebarFirstColor' => '#2b7b7d',
  'sidebarSecondColor' => '#2b7b7d',
  'sidebarGradientDegree' => '318deg',
  'primaryBtnColor1' => '#4ba1d7',
  'primaryBtnColor2' => '#4ba1d7',
  'secondryBtnColor' => '#21b618',
  'dropDownBtnColor' => '#265471',
  'btnOnHoverColor' => '#cbcbcb',
  'deleteBtnColor' => 'red',
  'delBtnHorizPadding' => '10',
  'delBtnVertPadding' => '20',
);
